### ISSUE TITLE
Installation error on MacOS

### ISSUE THREAD

**Issue by ghasem-abdi** [centreborelli/srtm4#13]
PLEASE ADVISE

Collecting srtm4
  Using cached srtm4-1.1.5.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: filelock in ./opt/anaconda3/lib/python3.8/site-packages (from srtm4) (3.4.0)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.8/site-packages (from srtm4) (1.21.4)
Requirement already satisfied: requests in ./opt/anaconda3/lib/python3.8/site-packages (from srtm4) (2.26.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->srtm4) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->srtm4) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->srtm4) (3.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->srtm4) (2.0.8)
Building wheels for collected packages: srtm4
  Building wheel for srtm4 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ghasem.abdi/opt/anaconda3/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py'"'"'; __file__='"'"'/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-wheel-7ht8x0fm
       cwd: /private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying srtm4.py -> build/lib
  running egg_info
  writing srtm4.egg-info/PKG-INFO
  writing dependency_links to srtm4.egg-info/dependency_links.txt
  writing requirements to srtm4.egg-info/requires.txt
  writing top-level names to srtm4.egg-info/top_level.txt
  listing git files failed - pretending there aren't any
  reading manifest file 'srtm4.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'requirements.txt'
  writing manifest file 'srtm4.egg-info/SOURCES.txt'
  mkdir -p bin
  c++ -g -O3 -fpermissive -DNDEBUG -DDONT_USE_TEST_MAIN -c src/Geoid.cpp -o src/Geoid.o
  c++ -g -O3 -fpermissive -DNDEBUG -DDONT_USE_TEST_MAIN -c src/geoid_height_wrapper.cpp -o src/geoid_height_wrapper.o
  cc -std=c99 -g -O3 -DNDEBUG -DDONT_USE_TEST_MAIN -DMAIN_SRTM4 src/srtm4.c src/Geoid.o src/geoid_height_wrapper.o -lstdc++ -lz -lm -ltiff -o bin/srtm4
  src/srtm4.c:9:10: fatal error: 'tiffio.h' file not found
  #include <tiffio.h>
           ^~~~~~~~~~
  1 error generated.
  make: *** [bin/srtm4] Error 1
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py", line 39, in <module>
      setup(name="srtm4",
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py", line 28, in run
      subprocess.check_call("make", shell=True)
    File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for srtm4
  Running setup.py clean for srtm4
Failed to build srtm4
Installing collected packages: srtm4
    Running setup.py install for srtm4 ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ghasem.abdi/opt/anaconda3/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py'"'"'; __file__='"'"'/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-record-0nvxixnl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ghasem.abdi/opt/anaconda3/include/python3.8/srtm4
         cwd: /private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/
    Complete output (55 lines):
    running install
    /Users/ghasem.abdi/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib
    copying srtm4.py -> build/lib
    running egg_info
    writing srtm4.egg-info/PKG-INFO
    writing dependency_links to srtm4.egg-info/dependency_links.txt
    writing requirements to srtm4.egg-info/requires.txt
    writing top-level names to srtm4.egg-info/top_level.txt
    listing git files failed - pretending there aren't any
    reading manifest file 'srtm4.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'requirements.txt'
    writing manifest file 'srtm4.egg-info/SOURCES.txt'
    cc -std=c99 -g -O3 -DNDEBUG -DDONT_USE_TEST_MAIN -DMAIN_SRTM4 src/srtm4.c src/Geoid.o src/geoid_height_wrapper.o -lstdc++ -lz -lm -ltiff -o bin/srtm4
    src/srtm4.c:9:10: fatal error: 'tiffio.h' file not found
    #include <tiffio.h>
             ^~~~~~~~~~
    1 error generated.
    make: *** [bin/srtm4] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py", line 39, in <module>
        setup(name="srtm4",
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py", line 28, in run
        subprocess.check_call("make", shell=True)
      File "/Users/ghasem.abdi/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ghasem.abdi/opt/anaconda3/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py'"'"'; __file__='"'"'/private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-install-h6i6i78q/srtm4_ba80b7fe0e044931b2a36f7990c443b5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tg/3j7jy4jd3gs_69pk4m00c7sw0000gn/T/pip-record-0nvxixnl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ghasem.abdi/opt/anaconda3/include/python3.8/srtm4 Check the logs for full command output.

**Comment by ellemiekevankints** [comment]
How did you resolve this error?
